# Use a Go base image
FROM golang:1.23 AS builder

# Set the Current Working Directory inside the container
WORKDIR /app/post-service

# Copy go mod and sum files
COPY post-service/go.mod post-service/go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY post-service/ .

# Build the Go app
RUN go build -o post-service cmd/main.go

# Start a new stage from scratch
FROM golang:1.23

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/post-service/post-service .

# Expose port 50051 to the outside world
EXPOSE 50051

# Command to run the executable
CMD ["./post-service"]
